apiVersion: batch/v1beta1
kind: CronJob
metadata:
 name: mibact-eventi-downloader
spec:
  # ogni giorno alle ore 13
  schedule: "0 11 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: mibact-eventi
        spec:
          containers:
          - name: mibact-eventi-downloader
            image: nexus.daf.teamdigitale.it/mibact-downloader:0.0.1
            env:
              - name: dataset
                value: eventi
              - name: sftp_host
                value: daf.teamdigitale.it
              - name: sftp_user
                value: pac_mibact_daf
              - name: sftp_key_file
                value: ./secret/pac_mibact_sftp-key
              - name: sftp_folder
                value: EDUC/XXX/mibact_eventi_culturali/
            volumeMounts:
            - name: glusterfsvol
              mountPath: /opt/mibact-downloader/logs
              subPath: mibact-downloader/logs
            - name: sftp-key
              mountPath: /opt/mibact-downloader/secret
              readOnly: true
          volumes:
          - name: glusterfsvol
            persistentVolumeClaim:
              claimName: gluster-claim
          - name: sftp-key
            secret:
              secretName: pa-secret
              items:
              - key: pac_mibact_sftp-key
                path: pac_mibact_sftp-key
          restartPolicy: OnFailure